document.writeln("<!DOCTYPE HTML PUBLIC \"-\/\/W3C\/\/DTD HTML 4.01 Transitional\/\/EN\">");
document.writeln("<head>");
document.writeln("<title>顶九网: 购物搜索,一个顶九! 顶九购物搜索信息平台  guide.ding9.com<\/title>");
document.writeln("<META NAME=\"description\" CONTENT=\"首页关键内容中国最好、最强、产品最多的比较购物平台，让您享受省时、省力、省钱、省心的购物环境，真正做到货比多家，购买到最好、最便宜的商品，体验比较购物的无限乐趣。\"> <META NAME=\"keywords\" CONTENT=\"首页关键词比较 购物 网站 价格 商家 商品 产品 品牌 购物网站 比较购物 在线购物 比较价格 商家比较  产品评价 商家评价 ding9.com 计算机 数码电子 办公设备 通讯 汽车 成人用品 家用电器 化妆品 音像\"><META NAME=\"Author\" CONTENT=\"顶九网\"> <META NAME=\"Subject\" CONTENT=\"顶九网 ding9网 ding9 顶九 ding9wang  比较 购物 省钱 便宜 商家 指南\"><META NAME=\"Robots\" CONTENT=\"all\"><META NAME=\"copyright\" CONTENT=\"ding9.com\">");
document.writeln("<meta http-equiv=\"Content-Type\" content=\"text\/html; charset=gb2312\" \/>");
document.writeln("<link href=\"http:\/\/union.ding9.com\/cooperate\/coopjs\/css3.0\/tefont.css\" rel=\"stylesheet\" type=\"text\/css\">");
document.writeln("<link href=\"http:\/\/union.ding9.com\/cooperate\/coopjs\/css3.0\/te.css\" rel=\"stylesheet\" type=\"text\/css\">");
document.writeln("<script type=\"text\/javascript\" src=\"http:\/\/union.ding9.com\/cooperate\/coopjs\/js\/tecomment.js\"><\/script>");
document.writeln("<script type=\"text\/javascript\" src=\"http:\/\/union.ding9.com\/cooperate\/coopjs\/js\/public.js\"><\/script>");
document.writeln("<script language=\"javascript\">");
document.writeln("var show_word=\"输入关键字进行搜索\";");
document.writeln("function showSearch(obj,type){");
document.writeln("	if(type){");
document.writeln("		if(obj.value==\"\")");
document.writeln("			obj.value=show_word;");
document.writeln("		obj.style.color=\'gray\';");
document.writeln("	}else{		");
document.writeln("		if(obj.value==show_word)");
document.writeln("			obj.value=\"\";");
document.writeln("		obj.style.color=\'#000000\';");
document.writeln("	}");
document.writeln("}");
document.writeln("");
document.writeln("function searchform_onsubmit() {");
document.writeln("	if(trim(document.searchform.key.value)==\'\'){");
document.writeln("		alert(\'请输入查询关键字\');");
document.writeln("		return false;");
document.writeln("	}");
document.writeln("	var sel_prso_id_one = document.searchform.prso_id_one.value;");
document.writeln("	if (sel_prso_id_one == \"\") {	\/\/所有类别");
document.writeln("		document.searchform.action=\"http:\/\/search.ding9.com\/search.do\";");
document.writeln("	}");
document.writeln("	if (sel_prso_id_one == \"1\") {	\/\/数码电子");
document.writeln("		document.searchform.action=\"http:\/\/digital.ding9.com\/search.do\";");
document.writeln("	}");
document.writeln("	if (sel_prso_id_one == \"4\") {	\/\/成人用品");
document.writeln("		document.searchform.action=\"http:\/\/love.ding9.com\/search.do\";");
document.writeln("	}");
document.writeln("	if (sel_prso_id_one == \"6\") {	\/\/手机\/通讯");
document.writeln("		document.searchform.action=\"http:\/\/mobile.ding9.com\/search.do\";");
document.writeln("	}");
document.writeln("	if (sel_prso_id_one == \"7\") {	\/\/电脑\/网络");
document.writeln("		document.searchform.action=\"http:\/\/computer.ding9.com\/search.do\";");
document.writeln("	}");
document.writeln("	if (sel_prso_id_one == \"8\") {	\/\/美容美体");
document.writeln("		document.searchform.action=\"http:\/\/beauty.ding9.com\/search.do\";");
document.writeln("	}");
document.writeln("	if (sel_prso_id_one == \"12\") {	\/\/家用电器");
document.writeln("		document.searchform.action=\"http:\/\/hea.ding9.com\/search.do\";");
document.writeln("	}");
document.writeln("	if (sel_prso_id_one == \"15\") {	\/\/办公用品");
document.writeln("		document.searchform.action=\"http:\/\/office.ding9.com\/search.do\";");
document.writeln("	}");
document.writeln("	return true;");
document.writeln("}");
document.writeln("  <\/script>");
document.writeln("<SCRIPT language=JavaScript type=text\/JavaScript>");
document.writeln("<!--");
document.writeln("function MM_reloadPage(init) {  \/\/reloads the window if Nav4 resized");
document.writeln("  if (init==true) with (navigator) {if ((appName==\"Netscape\")&&(parseInt(appVersion)==4)) {");
document.writeln("    document.MM_pgW=innerWidth; document.MM_pgH=innerHeight; onresize=MM_reloadPage; }}");
document.writeln("  else if (innerWidth!=document.MM_pgW || innerHeight!=document.MM_pgH) location.reload();");
document.writeln("}");
document.writeln("MM_reloadPage(true);");
document.writeln("");
document.writeln("function MM_callJS(jsStr) { \/\/v2.0");
document.writeln("  return eval(jsStr)");
document.writeln("}");
document.writeln("");
document.writeln("function MM_findObj(n, d) { \/\/v4.01");
document.writeln("  var p,i,x;  if(!d) d=document; if((p=n.indexOf(\"?\"))>0&&parent.frames.length) {");
document.writeln("    d=parent.frames[n.substring(p+1)].document; n=n.substring(0,p);}");
document.writeln("  if(!(x=d[n])&&d.all) x=d.all[n]; for (i=0;!x&&i<d.forms.length;i++) x=d.forms[i][n];");
document.writeln("  for(i=0;!x&&d.layers&&i<d.layers.length;i++) x=MM_findObj(n,d.layers[i].document);");
document.writeln("  if(!x && d.getElementById) x=d.getElementById(n); return x;");
document.writeln("}");
document.writeln("");
document.writeln("function MM_showHideLayers() { \/\/v6.0");
document.writeln("  var i,p,v,obj,args=MM_showHideLayers.arguments;");
document.writeln("  for (i=0; i<(args.length-2); i+=3) if ((obj=MM_findObj(args[i]))!=null) { v=args[i+2];");
document.writeln("    if (obj.style) { obj=obj.style; v=(v==\'show\')?\'visible\':(v==\'hide\')?\'hidden\':v; }");
document.writeln("    obj.visibility=v; }");
document.writeln("}");
document.writeln("\/\/-->");
document.writeln("<\/SCRIPT>");
document.writeln("");
document.writeln("<\/head>");
document.writeln("");
document.writeln("<body>");
document.writeln("<center>");
document.writeln("<div id=\"top\">");
document.writeln("<div id=\"top_1\"><img src=\"http:\/\/union.ding9.com\/cooperate\/coopjs\/teimages\/log03.gif\" width=\"13\" height=\"13\"><a href=\"http:\/\/guide.ding9.com\/switch----,help.htm\"  target=\"_blank\" class=\"teH1\"> 帮助<\/a><\/div>");
document.writeln("<div id=\"top_2\"><img src=\"http:\/\/union.ding9.com\/cooperate\/coopjs\/teimages\/log02.gif\" width=\"13\" height=\"13\"><span class=\"teH1\"><a href=\"http:\/\/merchant.ding9.com\/login.html\" target=\"_blank\" class=\"teH1\"> 商家登录<\/a>\/<a href=\"http:\/\/merchant.ding9.com\/register.html\" target=\"_blank\" class=\"teH1\">注册<\/a><\/span><\/div>");
document.writeln("<!-- div id=\"top_3\"><img src=\"http:\/\/union.ding9.com\/cooperate\/coopjs\/teimages\/log01.gif\" width=\"13\" height=\"13\"><span class=\"teH1\"><a href=\"#\" class=\"teH1\"> 用户登录<\/a>\/<a href=\"#\" class=\"teH1\">注册<\/a><\/span><\/div-->");
document.writeln("<\/div><!--top-->");
document.writeln("");
document.writeln("<div id=\"top001\">");
document.writeln("<div id=\"top001_l\"><a href=\"http:\/\/guide.ding9.com\" target=\"_blank\"><img src=\"http:\/\/union.ding9.com\/cooperate\/coopjs\/teimages\/logo.gif\" width=\"192\" height=\"108\" border=\"0\"><\/a><\/div>");
document.writeln("<div id=\"top001_m1\"><img src=\"http:\/\/union.ding9.com\/cooperate\/coopjs\/teimages\/top001.gif\" width=\"33\" height=\"108\"><\/div>");
document.writeln("<div id=\"top001_m2\">");
document.writeln("  <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" >");
document.writeln("    <tr>");
document.writeln("      <td align=\"center\"><table width=\"310\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" id=\"tesecTable1\">");
document.writeln("        <tr>");
document.writeln("          <td width=\"50\" class=\"tesel03\" onClick=\"tesecBoard1(0)\">商品<\/td>          ");
document.writeln("          <td width=\"50\" class=\"tesel04\" onClick=\"\">商家<\/td>          ");
document.writeln("          <td width=\"50\" class=\"tesel04\" onClick=\"\">优惠<\/td>          ");
document.writeln("          <td width=\"50\" class=\"tesel04\" onClick=\"\">促销<\/td>          ");
document.writeln("          <td width=\"50\" class=\"tesel04\" onClick=\"\">资讯<\/td>          ");
document.writeln("          <td width=\"50\" class=\"tesel04\" onClick=\"\">评论<\/td>");
document.writeln("        <\/tr>");
document.writeln("      <\/table><\/td>");
document.writeln("    <\/tr>");
document.writeln("  <\/table>");
document.writeln("  <table width=\"85%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" id=\"temainTable1\">");
document.writeln("    <tbody  style=\"display:block;\">");
document.writeln("	<tr>");
document.writeln("      <td><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
document.writeln("      <form name=\"searchform\" action=\"http:\/\/search.ding9.com\/search.do\" method=\"post\" onSubmit=\"return searchform_onsubmit()\" target=\"_blank\" >");
document.writeln("        <tr>");
document.writeln("          <td width=\"82%\" height=\"32\"><input name=\"key\" type=\"text\" class=\"teH4\" onblur=showSearch(this,1) onfocus=showSearch(this) value=\"输入关键字进行搜索\" size=\"54\">");
document.writeln("              <select name=\"prso_id_one\"  class=\"teH1\" >");
document.writeln("                      <option>所有类别<\/option>");
document.writeln("                      <option value=\"1\" >数码\/电子<\/option>");
document.writeln("                      <option value=\"4\">成人用品<\/option>");
document.writeln("                      <option value=\"6\">手机\/通讯<\/option>");
document.writeln("                      <option value=\"7\">电脑\/网络<\/option>");
document.writeln("                      <option value=\"8\" selected>美容美体<\/option>");
document.writeln("                      <option value=\"12\">家用电器<\/option>");
document.writeln("                      <option value=\"15\">办公用品<\/option>");
document.writeln("                  <\/select>        <\/td>");
document.writeln("          <td width=\"18%\"><input type=\"image\" src=\"teimages\/s001.gif\" width=\"103\" height=\"22\" border=\"0\"><\/td>");
document.writeln("        <\/tr>      ");
document.writeln("        <tr>");
document.writeln("										<td height=\"19\" colspan=\"2\" class=\"teH1c\">热门搜索:<a target=\"_blank\" href=\"http:\/\/search.ding9.com\/search----,诺基亚.htm\"><span class=\'teH1\'>诺基亚<\/span><\/a>");
document.writeln("<a target=\"_blank\" href=\"http:\/\/search.ding9.com\/search----,索尼爱立信.htm\"><span class=\'teH1\'>索尼爱立信<\/span><\/a>");
document.writeln("<a target=\"_blank\" href=\"http:\/\/search.ding9.com\/search----,三星.htm\"><span class=\'teH1\'>三星<\/span><\/a>");
document.writeln("<a target=\"_blank\" href=\"http:\/\/search.ding9.com\/search----,苹果.htm\"><span class=\'teH1\'>苹果<\/span><\/a>");
document.writeln("<a target=\"_blank\" href=\"http:\/\/search.ding9.com\/search----,索尼.htm\"><span class=\'teH1\'>索尼<\/span><\/a>");
document.writeln("<a target=\"_blank\" href=\"http:\/\/search.ding9.com\/search----,兰蔻.htm\"><span class=\'teH1\'>兰蔻<\/span><\/a>");
document.writeln("<a target=\"_blank\" href=\"http:\/\/search.ding9.com\/search----,剃须刀.htm\"><span class=\'teH1\'>剃须刀<\/span><\/a>");
document.writeln("<a target=\"_blank\" href=\"http:\/\/search.ding9.com\/search----,美容.htm\"><span class=\'teH1\'>美容<\/span><\/a>");
document.writeln("<\/td>");
document.writeln("          <\/tr>   <\/form> ");
document.writeln("      <\/table><\/td>");
document.writeln("    <\/tr><\/tbody>");
document.writeln("	");
document.writeln("	");
document.writeln("	 <tbody  style=\"display:none;\">");
document.writeln("	<tr>");
document.writeln("      <td><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
document.writeln("        <tr>");
document.writeln("          <td width=\"82%\" height=\"32\"><input name=\"textfield\" type=\"text\" class=\"teH4\" value=\"输入关键字进行搜索\" size=\"40\">");
document.writeln("              <select name=\"select\" class=\"teH1\">");
document.writeln("                <option>所在省份<\/option>");
document.writeln("              <\/select>");
document.writeln("              <select name=\"select2\" class=\"teH1\">");
document.writeln("                <option>所在城市<\/option>");
document.writeln("                    <\/select><\/td>");
document.writeln("          <td width=\"18%\"><a href=\"#\"><img src=\"http:\/\/union.ding9.com\/cooperate\/coopjs\/teimages\/s002.gif\" width=\"103\" height=\"22\" border=\"0\"><\/a><\/td>");
document.writeln("        <\/tr>");
document.writeln("        <tr>");
document.writeln("          <td height=\"19\" colspan=\"2\" class=\"teH1c\">热门搜索:&nbsp;<A href=\"http:\/\/merchant.ding9.com\/member\/merchant-list.do?key=MP3\" target=\"_blank\" class=\"teH1\">MP3<\/A> <A href=\"http:\/\/merchant.ding9.com\/member\/merchant-list.do?key=数码\" target=\"_blank\" class=\"teH1\">数码<\/A> <A href=\"http:\/\/merchant.ding9.com\/member\/merchant-list.do?key=IT\" target=\"_blank\" class=\"teH1\">IT<\/A> <A href=\"http:\/\/merchant.ding9.com\/member\/merchant-list.do?key=手机\" target=\"_blank\" class=\"teH1\">手机<\/A> <A href=\"http:\/\/merchant.ding9.com\/member\/merchant-list.do?key=通讯\" target=\"_blank\" class=\"teH1\">通讯<\/A> <A href=\"http:\/\/merchant.ding9.com\/member\/merchant-list.do?key=移动\" target=\"_blank\" class=\"teH1\">移动<\/A><\/td>");
document.writeln("          <\/tr>");
document.writeln("      <\/table><\/td>");
document.writeln("    <\/tr><\/tbody>");
document.writeln("		 <tbody  style=\"display:none;\">");
document.writeln("	<tr>");
document.writeln("      <td><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
document.writeln("        <tr>");
document.writeln("          <td width=\"82%\" height=\"32\"><input name=\"textfield\" type=\"text\" class=\"teH4\" value=\"输入关键字进行搜索\" size=\"68\"><\/td>");
document.writeln("          <td width=\"18%\"><a href=\"#\"><img src=\"http:\/\/union.ding9.com\/cooperate\/coopjs\/teimages\/s003.gif\" width=\"103\" height=\"22\" border=\"0\"><\/a><\/td>");
document.writeln("        <\/tr>");
document.writeln("        <tr>");
document.writeln("          <td height=\"19\" colspan=\"2\" class=\"teH1c\">热门搜索:&nbsp;<A href=\"http:\/\/search.ding9.com\/cheapcard.do?q=手机\" target=\"_blank\" class=\"teH1\">手机<\/A> <A href=\"http:\/\/search.ding9.com\/cheapcard.do?q=数码\" target=\"_blank\" class=\"teH1\">数码<\/A> <A href=\"http:\/\/search.ding9.com\/cheapcard.do?q=化妆\" target=\"_blank\" class=\"teH1\">化妆<\/A> <A href=\"http:\/\/search.ding9.com\/cheapcard.do?q=电脑\" target=\"_blank\" class=\"teH1\">电脑<\/A> <A href=\"http:\/\/search.ding9.com\/cheapcard.do?q=成人\" target=\"_blank\" class=\"teH1\">成人<\/A> <A href=\"http:\/\/search.ding9.com\/cheapcard.do?q=诺基亚\" target=\"_blank\" class=\"teH1\">诺基亚<\/A> <A href=\"http:\/\/search.ding9.com\/cheapcard.do?q=耳机\" target=\"_blank\" class=\"teH1\">耳机<\/A> <A href=\"http:\/\/search.ding9.com\/cheapcard.do?q=优惠券\" target=\"_blank\" class=\"teH1\">优惠券<\/A> <A href=\"http:\/\/search.ding9.com\/cheapcard.do?q=现金券\" target=\"_blank\" class=\"teH1\">现金券<\/A><\/td>");
document.writeln("          <\/tr>");
document.writeln("      <\/table><\/td>");
document.writeln("    <\/tr><\/tbody>");
document.writeln("	");
document.writeln("	");
document.writeln("  	 <tbody  style=\"display:none;\">");
document.writeln("	<tr>");
document.writeln("      <td><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
document.writeln("        <tr>");
document.writeln("          <td width=\"82%\" height=\"32\"><input name=\"textfield\" type=\"text\" class=\"teH4\" value=\"输入关键字进行搜索\" size=\"68\"><\/td>");
document.writeln("          <td width=\"18%\"><a href=\"#\"><img src=\"http:\/\/union.ding9.com\/cooperate\/coopjs\/teimages\/s004.gif\" width=\"103\" height=\"22\" border=\"0\"><\/a><\/td>");
document.writeln("        <\/tr>");
document.writeln("        <tr>");
document.writeln("          <td height=\"19\" colspan=\"2\" class=\"teH1c\">热门搜索:&nbsp;<A href=\"http:\/\/search.ding9.com\/promotion.do?q=促销\" target=\"_blank\" class=\"teH1\">促销<\/A> <A href=\"http:\/\/search.ding9.com\/promotion.do?q=硬盘\" target=\"_blank\" class=\"teH1\">硬盘<\/A> <A href=\"http:\/\/search.ding9.com\/promotion.do?q=护理\" target=\"_blank\" class=\"teH1\">护理<\/A> <A href=\"http:\/\/search.ding9.com\/promotion.do?q=纤体\" target=\"_blank\" class=\"teH1\">纤体<\/A> <A href=\"http:\/\/search.ding9.com\/promotion.do?q=优惠\" target=\"_blank\" class=\"teH1\">优惠<\/A> <A href=\"http:\/\/search.ding9.com\/promotion.do?q=数码\" target=\"_blank\" class=\"teH1\">数码<\/A> <A href=\"http:\/\/search.ding9.com\/promotion.do?q=手机\" target=\"_blank\" class=\"teH1\">手机<\/A> <A href=\"http:\/\/search.ding9.com\/promotion.do?q=化妆品\" target=\"_blank\" class=\"teH1\">化妆品<\/A><\/td>");
document.writeln("          <\/tr>");
document.writeln("      <\/table><\/td>");
document.writeln("    <\/tr><\/tbody>");
document.writeln("	");
document.writeln("	");
document.writeln("  	 <tbody  style=\"display:none;\">");
document.writeln("	<tr>");
document.writeln("      <td><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
document.writeln("        <tr>");
document.writeln("          <td width=\"82%\" height=\"32\"><input name=\"textfield3\" type=\"text\" class=\"teH4\" value=\"输入关键字进行搜索\" size=\"68\"><\/td>");
document.writeln("          <td width=\"18%\"><a href=\"#\"><img src=\"http:\/\/union.ding9.com\/cooperate\/coopjs\/teimages\/s005.gif\" width=\"103\" height=\"22\" border=\"0\"><\/a><\/td>");
document.writeln("        <\/tr>");
document.writeln("        <tr>");
document.writeln("          <td height=\"19\" colspan=\"2\" class=\"teH1c\">热门搜索:&nbsp;<A href=\"http:\/\/search.ding9.com\/article.do?q=手机\" target=\"_blank\" class=\"teH1\">手机<\/A> <A href=\"http:\/\/search.ding9.com\/article.do?q=笔记本\" target=\"_blank\" class=\"teH1\">笔记本<\/A> <A href=\"http:\/\/search.ding9.com\/article.do?q=美白\" target=\"_blank\" class=\"teH1\">美白<\/A> <A href=\"http:\/\/search.ding9.com\/article.do?q=数码相机\" target=\"_blank\" class=\"teH1\">数码相机<\/A> <A href=\"http:\/\/search.ding9.com\/article.do?q=MP3\" target=\"_blank\" class=\"teH1\">MP3<\/A><\/td>");
document.writeln("          <\/tr>");
document.writeln("      <\/table><\/td>");
document.writeln("    <\/tr><\/tbody>");
document.writeln("	");
document.writeln("	");
document.writeln("  	 <tbody  style=\"display:none;\">");
document.writeln("	<tr>");
document.writeln("      <td><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
document.writeln("        <tr>");
document.writeln("          <td width=\"82%\" height=\"32\"><input name=\"textfield\" type=\"text\" class=\"teH4\" value=\"输入关键字进行搜索\" size=\"54\">");
document.writeln("              <select name=\"select\" class=\"teH1\">");
document.writeln("                <option>所在类别<\/option>");
document.writeln("              <\/select>          <\/td>");
document.writeln("          <td width=\"18%\"><a href=\"#\"><img src=\"http:\/\/union.ding9.com\/cooperate\/coopjs\/teimages\/s006.gif\" width=\"103\" height=\"22\" border=\"0\"><\/a><\/td>");
document.writeln("        <\/tr>");
document.writeln("        <tr>");
document.writeln("          <td height=\"19\" colspan=\"2\" class=\"teH1c\">热门搜索:&nbsp;<A href=\"http:\/\/search.ding9.com\/comment.do?q=N73\" target=\"_blank\" class=\"teH1\">N73<\/A> <A href=\"http:\/\/search.ding9.com\/comment.do?q=摩托罗拉\" target=\"_blank\" class=\"teH1\">摩托罗拉<\/A> <A href=\"http:\/\/search.ding9.com\/comment.do?q=PDA\" target=\"_blank\" class=\"teH1\">PDA<\/A> <A href=\"http:\/\/search.ding9.com\/comment.do?q=丰胸\" target=\"_blank\" class=\"teH1\">丰胸<\/A> <A href=\"http:\/\/search.ding9.com\/comment.do?q=彩妆\" target=\"_blank\" class=\"teH1\">彩妆<\/A><\/td>");
document.writeln("          <\/tr>");
document.writeln("      <\/table><\/td>");
document.writeln("    <\/tr><\/tbody>");
document.writeln("	");
document.writeln("	");
document.writeln("  ");
document.writeln("	");
document.writeln("	");
document.writeln("  <\/table>");
document.writeln("  <\/div>");
document.writeln("<!--top001m2-->");
document.writeln("<div id=\"top001_r\"><img src=\"http:\/\/union.ding9.com\/cooperate\/coopjs\/teimages\/top003.gif\" width=\"49\" height=\"108\"><\/div>");
document.writeln("<\/div><!--top001-->");
document.writeln("");
document.writeln("<div id=\"menu\">");
document.writeln("<div id=\"menu_l\"><img src=\"http:\/\/union.ding9.com\/cooperate\/coopjs\/teimages\/menu001.gif\" width=\"8\" height=\"26\"><\/div>");
document.writeln("<div  id=\"menu_2\"><a href=\"http:\/\/guide.ding9.com\" class=\"teH1\"  target=\"_top\">首   页<\/a><\/div>");
document.writeln("<div class=\"teH1\" id=\"menu_1\"><a href=\"http:\/\/mobile.ding9.com\" class=\"teH1\" target=\"_top\">手机通信<\/a><\/div>");
document.writeln("<div id=\"menu_3\"><a href=\"http:\/\/digital.ding9.com\" class=\"teH1\" target=\"_top\">数码电子<\/a><\/div>");
document.writeln("<div id=\"menu_4\"><a href=\"http:\/\/computer.ding9.com\" class=\"teH1\" target=\"_top\">电脑网络<\/a><\/div>");
document.writeln("<div id=\"menu_5\"><a href=\"http:\/\/office.ding9.com\" class=\"teH1\" target=\"_top\">办公用品<\/a><\/div>");
document.writeln("<div id=\"menu_6\"><a href=\"http:\/\/hea.ding9.com\" class=\"teH1\" target=\"_top\">家用电器<\/a><\/div>");
document.writeln("<div id=\"menu_m\"><a href=\"http:\/\/beauty.ding9.com\" class=\"teH1\" target=\"_top\">美容美体<\/a><\/div>");
document.writeln("<div id=\"menu_8\"><a href=\"http:\/\/love.ding9.com\" class=\"teH1\" target=\"_top\">成人用品<\/a><\/div>");
document.writeln("<div class=\"teH1\" id=\"menu_9\"><a  href=\"http:\/\/coupon.ding9.com\" class=\"teH1\" target=\"_top\">优惠券<\/a><\/div>");
document.writeln("<div id=\"menu_10\"><a href=\"http:\/\/promotion.ding9.com\" class=\"teH1\" target=\"_top\">促销折扣<\/a><\/div>");
document.writeln("<div id=\"menu_12\"><a href=\"http:\/\/search.ding9.com\" class=\"H2\" target=\"_top\"><img src=\"http:\/\/union.ding9.com\/cooperate\/coopjs\/teimages\/gj.gif\" width=\"50\" height=\"18\" border=\"0\"><\/a><\/div>");
document.writeln("<div id=\"menu_11\"><a href=\"http:\/\/gz.shoplocal.ding9.com\" class=\"teH1\" target=\"_top\">我爱逛街<\/a><\/div>");
document.writeln("<div id=\"menu_13\" onMouseOver=\"MM_showHideLayers(\'Layer2\',\'\',\'show\')\" ");
document.writeln("    onmouseout=\"MM_showHideLayers(\'Layer2\',\'\',\'hide\')\" vAlign=center ");
document.writeln("    align=middle width=72><a class=\"teH1\">更多 <\/a><img src=\"http:\/\/union.ding9.com\/cooperate\/coopjs\/teimages\/arrow_022.gif\" width=\"8\" height=\"8\" border=\"0\"><\/div>");
document.writeln("<div id=\"menu_r\"><img src=\"http:\/\/union.ding9.com\/cooperate\/coopjs\/teimages\/menu004.gif\" width=\"8\" height=\"26\"><\/div>");
document.writeln("");
document.writeln("");
document.writeln("<\/div><!--menu-->");
document.writeln("<DIV id=Layer1 ");
document.writeln("      style=\"Z-INDEX: 1; WIDTH: 72px; POSITION: absolute; HEIGHT: 23px; \">");
document.writeln("  <DIV id=Layer2 onMouseOver=\"MM_showHideLayers(\'Layer2\',\'\',\'show\')\" ");
document.writeln("      style=\"Z-INDEX: 1; LEFT: 828px; VISIBILITY: hidden; WIDTH: 72px; POSITION: absolute; TOP: -2px; HEIGHT: 61px\" ");
document.writeln("      onmouseout=\"MM_showHideLayers(\'Layer2\',\'\',\'hide\')\">");
document.writeln("    <TABLE width=\"100%\" ");
document.writeln("        border=0 cellPadding=0 cellSpacing=1 bgColor=#CCCCCC >");
document.writeln("      <TBODY>");
document.writeln("        <TR>");
document.writeln("          <TD height=\"25\" class=service onMouseOver=\"this.className=\'service-blank\'\" ");
document.writeln("          onmouseout=\"this.className=\'service\'\" bgColor=#F7FBFD><A ");
document.writeln("            href=\"http:\/\/merchant.ding9.com\" class=\"teH1\" target=\"_top\">&nbsp;顶九商家<\/A><\/TD>");
document.writeln("        <\/TR>");
document.writeln("        <TR>");
document.writeln("          <TD height=\"25\" class=service onMouseOver=\"this.className=\'service-blank\'\" ");
document.writeln("          onmouseout=\"this.className=\'service\'\" bgColor=#F7FBFD><A ");
document.writeln("            href=\"http:\/\/youhui.ding9.com\" class=\"teH1\" target=\"_top\">&nbsp;优惠在线<\/A><\/TD>");
document.writeln("        <\/TR>");
document.writeln("		<TR>");
document.writeln("          <TD height=\"25\" class=service onMouseOver=\"this.className=\'service-blank\'\" ");
document.writeln("          onmouseout=\"this.className=\'service\'\" bgColor=#F7FBFD><A ");
document.writeln("            href=\"http:\/\/carcv.ding9.com\" class=\"teH1\" target=\"_top\">&nbsp;二手车<\/A><\/TD>");
document.writeln("        <\/TR>");
document.writeln("        <TR>");
document.writeln("          <TD height=\"25\" class=service onMouseOver=\"this.className=\'service-blank\'\" ");
document.writeln("          onmouseout=\"this.className=\'service\'\" bgColor=#F7FBFD><A ");
document.writeln("            href=\"http:\/\/www.smartclub.com.cn\/sp_channel\/index.asp?site=ding9\" class=\"teH1\" target=\"_top\">&nbsp;积分奖励<\/A><\/TD>");
document.writeln("        <\/TR>");
document.writeln("  <\/TBODY>");
document.writeln("    <\/TABLE>");
document.writeln("  <\/DIV>");
document.writeln("<\/DIV>");
document.writeln("<!--c02-->");
document.writeln("<div id=\"c03\">");
document.writeln("  <!--c03_l-->");
document.writeln("  <!--c03_r-->");
document.writeln("<\/div>");
document.writeln("<\/center>")